### ISSUE TITLE
Austin used for a small C programs with floating-point numbers

### ISSUE THREAD

**Issue by zell08v** [kiranlak/austin-sbst#1]
Hello, I am wondering whether it is possible to run Austin for a small C programs with floating-point numbers? As an example program:

int func(double x){
  if x<=5 return 10;
  else return 100;
}

Is that possible to use Austin to generate test inputs for the branches of 'func'? An expected set of inputs here may be {2,10}.

Thanks.

**Comment by kiranlak** [comment]
Yes, that is possible.
